### ISSUE TITLE
Multi-line docstring MetaModelica breaking highlighting

### ISSUE THREAD

**Issue by AnHeuermann** [AnHeuermann/metamodelica-language-vscode#41]
```modelica
public function createFMISimulationFlags
  "Function reads FMI simulation flags from user input --fmiFlags
   and creates FmiSimulationFlags record for code generation.
   Author: AnHeuermann"
  input Boolean printWarning = true;
  output Option<SimCode.FmiSimulationFlags> fmiSimulationFlags;
// [...]
end createFMISimulationFlags;
```

![grafik](https://github.com/AnHeuermann/metamodelica-language-vscode/assets/38031952/023c7b0d-0a91-44d7-8fba-5275fbb0e887)

**Comment by AnHeuermann** [comment]
@phannebohm I can't find a way of fixing this besides removing your

```yml
  - match: (?<![=+]\s*)((?<!\\)"([^"]*|\\")*(?<!\\)")\s*;
    captures:
      1:
        name: comment.line
```

Also regex101 isn't allowing the regex: https://regex101.com/r/a6GKMy/1

This means we can't detect doc strings after a variable declaration any more, but that's better than having all classes with documentation breaking the highlighting.
